# Generated by Django 3.2.25 on 2024-06-25 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_email_openinghours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openinghours',
            name='Hours',
        ),
        migrations.CreateModel(
            name='Hours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hours', models.CharField(max_length=200)),
                ('days', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.openinghours')),
            ],
        ),
    ]
