# Generated by Django 3.2.25 on 2024-06-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_fenster_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='fenster',
            name='innerTitle',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
