# Generated by Django 3.2.25 on 2024-06-26 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_fenster_innertitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='KunAluFensterPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='AluFenster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('innerTitle', models.CharField(max_length=250)),
                ('text', models.TextField(blank=True, null=True)),
                ('bottom', models.CharField(max_length=250)),
                ('fensterpage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.kunalufensterpage')),
            ],
        ),
    ]
