# Generated by Django 3.2.25 on 2024-06-26 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20240626_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolzAluFensterPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HolzAluFenster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('innerTitle', models.CharField(blank=True, max_length=250, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('bottom', models.CharField(blank=True, max_length=250, null=True)),
                ('fensterpage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.holzalufensterpage')),
            ],
        ),
    ]
