# Generated by Django 3.2.25 on 2024-06-26 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_holzalufenster_holzalufensterpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holzalufenster',
            name='image',
        ),
        migrations.CreateModel(
            name='HolzAluImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('holzalufenster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.holzalufenster')),
            ],
        ),
    ]
