# Generated by Django 3.2.25 on 2024-06-26 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20240626_1233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holzalusidepoints',
            options={'verbose_name': 'Side Point'},
        ),
        migrations.CreateModel(
            name='HolzAluBottomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('holzalufenster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.holzalufenster')),
            ],
            options={
                'verbose_name': 'Bottom Image',
            },
        ),
    ]
