# Generated by Django 3.2.25 on 2024-06-26 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_remove_holzalufenster_fensterpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolzFenster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HolzSidePoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('holzfenster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.holzfenster')),
            ],
            options={
                'verbose_name': 'Side Point',
            },
        ),
        migrations.CreateModel(
            name='HolzImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('holzfenster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.holzfenster')),
            ],
            options={
                'verbose_name': 'Carousel Image',
            },
        ),
        migrations.CreateModel(
            name='HolzBottomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('holzfenster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.holzfenster')),
            ],
            options={
                'verbose_name': 'Bottom Image',
            },
        ),
    ]
