# Generated by Django 3.2.25 on 2024-06-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_holzbottomimage_holzfenster_holzimages_holzsidepoints'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurenPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('button_text', models.CharField(blank=True, max_length=250, null=True)),
                ('button_link', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
