# Generated by Django 3.2.25 on 2024-06-26 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_turenpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToranLagenPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ToranLangenImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('toranpage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.toranlagenpage')),
            ],
        ),
    ]
