# Generated by Django 3.2.25 on 2024-06-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_toranlagenpage_toranlangenimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='toranlagenpage',
            name='inner_title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='toranlagenpage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
