# Generated by Django 3.2.25 on 2024-06-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_link', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
